# errorHandling
In this file we are handling the error using require(), revert() and assert() function.




